#custom events
PLAYER_SCORED = 1
PLAYER_DIED = 2

SCREEN_WIDTH = 800
SCREEN_HEIGHT = 480

HALF_SCREEN_WIDTH = SCREEN_WIDTH * 0.5
HALF_SCREEN_HEIGHT = SCREEN_HEIGHT * 0.5

#Makes debug elements visible 
DEBUG = False

